[package]
name = "aoc_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
itertools = "0.10.5"
nom = "7.1.3"
num = "0.4.0"
